# Generated by Django 5.2.1 on 2025-05-09 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('easyaudit', '0004_auto_20170620_1354_squashed_0019_alter_crudevent_changed_fields_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestEventExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='easyaudit.requestevent')),
            ],
        ),
    ]
